version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
        volumes:
            - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: fastcast
            MYSQL_USER: fastcast
            MYSQL_PASSWORD: fAsTcAsT123@
            SA_PASSWORD: "fAsTcAsT123@"
            ACCEPT_EULA: "Y"
        

